spring:
  application:
    name: tarae

  datasource:
    url: jdbc:mysql://localhost:3307/tarae?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: tarae
    password: tarae1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: dummy  # Security 자동 설정 비활성화용 (임시)
