server:
  servlet:
    session:
      timeout: 3h
      cookie:
        http-only: true
        secure: false

spring:
  application:
    name: tarae

  datasource:
    url: jdbc:mysql://localhost:3307/tarae?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: tarae
    password: tarae1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
